service: hello-world-api-ts
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 30330

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  region: us-east-1
  deploymentMethod: direct

functions:
  helloWorldGet:
    handler: src/handlers/index/get.handler
    events:
      - httpApi:
          path: /
          method: get
